sudo: required
services:
  - docker

before_install:
  - docker build -t doutside/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run doutside/react-test npm test --space --coverage

after_success:
  - docker build -t doutside/multi-client ./client
  - docker build -t doutside/multi-nginx ./nginx
  - docker build -t doutside/multi-server ./server
  - docker build -t doutside/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push doutside/multi-client
  - docker push doutside/multi-nginx
  - docker push doutside/multi-server
  - docker push doutside/multi-worker